import{a as w,S as b,i as y}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const L="44238533-8b617bda18ddca61b92d6b256",E="https://pixabay.com/api/";async function f(t,o=1,n=15){try{return(await w.get(E,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:n}})).data}catch{throw new Error("Network response was not ok")}}function I(t){t.innerHTML=""}function v(t){t.style.display="block"}function u(t){t.style.display="none"}function h(t,o){const n=t.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}">
        <div>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </a>
    `).join("");o.insertAdjacentHTML("beforeend",n),new b(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function p(t){y.error({title:"Error",message:t})}function m(t){y.info({title:"Info",message:t})}const B=document.getElementById("search-form"),g=document.getElementById("search-input"),a=document.getElementById("gallery"),c=document.getElementById("loader"),d=document.getElementById("load-more-btn");let l=1;B.addEventListener("submit",async t=>{t.preventDefault();const o=g.value.trim();if(o===""){p("Search query cannot be empty!");return}I(a),v(c);try{const n=await f(o);u(c);const s=n.hits;if(s.length===0){m("Sorry, there are no images matching your search query. Please try again!");return}h(s,a),d.style.display="block"}catch(n){u(c),p("Something went wrong. Please try again later."),console.error(n)}});d.addEventListener("click",async()=>{l++;try{const t=await f(g.value.trim(),l);h(t.hits,a),window.scrollBy({top:a.getBoundingClientRect().height*2,behavior:"smooth"}),(t.hits.length===0||t.totalHits<=l*perPage)&&(d.style.display="none",m("We're sorry, but you've reached the end of search results."))}catch(t){console.error(t)}});
//# sourceMappingURL=commonHelpers.js.map
