import{a as b,S as L,i as f}from"./assets/vendor-b11e2a50.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const E="44238533-8b617bda18ddca61b92d6b256",I="https://pixabay.com/api/";async function m(e,n=1,t=15){try{return(await b.get(I,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:t}})).data}catch{throw new Error("Network response was not ok")}}function v(e){e.innerHTML=""}galleryElement.insertAdjacentHTML("beforeend",markup);const B=new L(".gallery a",{captionsData:"alt",captionDelay:250});B.refresh();function P(e){e.style.display="block"}function y(e){e.style.display="none"}function h(e,n){e.map(t=>`
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}">
        <div>
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </a>
    `).join("")}function p(e){f.error({title:"Error",message:e})}function g(e){f.info({title:"Info",message:e})}const S=document.getElementById("search-form"),w=document.getElementById("search-input"),c=document.getElementById("gallery"),u=document.getElementById("loader"),a=document.getElementById("load-more-btn");let i=1;const l=15;S.addEventListener("submit",async e=>{e.preventDefault();const n=w.value.trim();if(n===""){p("Search query cannot be empty!");return}v(c),P(u),i=1,a.style.display="none";try{const t=await m(n,i,l);y(u);const s=t.hits;if(s.length===0){g("Sorry, there are no images matching your search query. Please try again!");return}h(s,c),s.length<l?a.style.display="none":a.style.display="block"}catch(t){y(u),a.style.display="none",p("Something went wrong. Please try again later."),console.error(t)}});a.addEventListener("click",async()=>{i++;try{const e=await m(w.value.trim(),i,l);h(e.hits,c),window.scrollBy({top:c.getBoundingClientRect().height*2,behavior:"smooth"}),(e.hits.length<l||e.totalHits<=i*l)&&(a.style.display="none",g("We're sorry, but you've reached the end of search results."))}catch(e){console.error(e)}});
//# sourceMappingURL=commonHelpers.js.map
